export const careerShopPolicy = {
  checkedAt: "2026-07-13",
  associateTag: "saunastampral-22",
  disclosure: "PR：Amazonのアソシエイトとして、manapickは適格販売により収入を得ています。",
  independence: "報酬額、承認状況、EPC、在庫、レビュー数を掲載順に使いません。価格・在庫・配送・仕様は購入前に販売ページとメーカー公式ページで確認してください。",
};

export const careerShopProducts = [
  {
    id: "anker-powerconf-s500",
    image: "/shop/meeting-speakerphone-illustration.svg",
    imageAlt: "会議用スピーカーフォンの編集部作成イメージ（実際の商品写真ではありません）",
    imageCredit: "画像：manapick編集部作成イメージ（実物と異なります）",
    category: "面接・会議",
    maker: "Anker",
    name: "Anker PowerConf S500",
    fit: "オンライン面接や複数人のキャリア相談で、PC内蔵マイクより会話を聞き取りやすくしたい人",
    reason: "話す内容を整えていても、音が途切れると伝わりません。S500は会議用スピーカーフォンとして、声を拾う場所と聞く場所を1台にまとめたいときの候補です。1人だけの録音品質を最優先するならUSBマイクも比較します。",
    checks: ["会議用か1人録音用か", "USB-C / Bluetooth接続", "部屋の反響と設置位置"],
    sourceId: "anker-powerconf-s500-official",
    officialUrl: "https://www.ankerjapan.com/products/a3305",
    amazonUrl: "https://www.amazon.co.jp/s?k=Anker+PowerConf+S500&tag=saunastampral-22",
  },
  {
    id: "dell-u3225qe",
    image: "/shop/monitor-illustration.svg",
    imageAlt: "作業用モニターの編集部作成イメージ（実際の商品写真ではありません）",
    imageCredit: "画像：manapick編集部作成イメージ（実物と異なります）",
    category: "調査・ポートフォリオ",
    maker: "Dell",
    name: "Dell U3225QE",
    fit: "求人条件、公式出典、自分の制作物を並べ、画面の往復を減らしたい人",
    reason: "大画面は採用可能性を上げる道具ではありません。一方で、31.5インチ4Kとハブ機能を持つこのモデルは、調査・学習・ポートフォリオ編集を同じ机で行う場合に、作業領域と配線をまとめる候補になります。",
    checks: ["机の幅と視聴距離", "PCの映像出力", "必要なUSB・LAN端子"],
    sourceId: "dell-u3225qe-official",
    officialUrl: "https://www.dell.com/ja-jp/shop/u3225qe-monitor/apd/210-BQMM/monitors-monitor-accessories",
    amazonUrl: "https://www.amazon.co.jp/s?k=Dell+U3225QE&tag=saunastampral-22",
  },
  {
    id: "stream-deck-neo",
    image: "/shop/macro-pad-illustration.svg",
    imageAlt: "反復操作用ボタンデバイスの編集部作成イメージ（実際の商品写真ではありません）",
    imageCredit: "画像：manapick編集部作成イメージ（実物と異なります）",
    category: "学び直し・反復",
    maker: "Elgato",
    name: "Stream Deck Neo",
    fit: "学習ページ、記録シート、会議操作など、同じ準備を何度も繰り返す人",
    reason: "8個のカスタムキーに、教材を開く、学習時間を記録する、マイクを切るなどの操作を割り当てられます。買う前にOS標準のショートカットで3つの反復操作を試し、それでも続く手間だけを機器へ移す考え方です。",
    checks: ["自動化したい操作を3つ決める", "対応OS", "USB-C接続"],
    sourceId: "elgato-stream-deck-neo-official",
    officialUrl: "https://www.elgato.com/jp/ja/p/stream-deck-neo",
    amazonUrl: "https://www.amazon.co.jp/dp/B0CWL3V6R8?tag=saunastampral-22",
  },
  {
    id: "sandisk-extreme-portable-ssd",
    image: "/shop/portable-drive-illustration.svg",
    imageAlt: "携帯型ストレージの編集部作成イメージ（実際の商品写真ではありません）",
    imageCredit: "画像：manapick編集部作成イメージ（実物と異なります）",
    category: "作品・バックアップ",
    maker: "SanDisk",
    name: "SanDisk Extreme Portable SSD",
    fit: "制作物、応募書類、学習データをPC本体とは別の場所にも保管したい人",
    reason: "ポートフォリオや応募書類は、作ることと同じくらい失わないことが重要です。外付けSSDは持ち運べますが、これ1台だけを唯一の保存先にはせず、クラウドや別媒体との二重化を前提に選びます。",
    checks: ["必要容量", "PC側のUSB仕様", "別のバックアップ先"],
    sourceId: "sandisk-extreme-official",
    officialUrl: "https://www.sandisk.com/ja-jp/products/ssd/external-ssd/portable-ssd-sandisk-extreme-usb-3-2?sku=61-200-25",
    amazonUrl: "https://www.amazon.co.jp/s?k=SanDisk+Extreme+Portable+SSD&tag=saunastampral-22",
  },
  {
    id: "mx-master-3s",
    image: "/shop/mouse-illustration.svg",
    imageAlt: "多機能マウスの編集部作成イメージ（実際の商品写真ではありません）",
    imageCredit: "画像：manapick編集部作成イメージ（実物と異なります）",
    category: "入力・資料整理",
    maker: "Logicool",
    name: "Logicool MX Master 3S",
    fit: "長い職業情報、表計算、制作ツールを行き来し、スクロールや定型操作が多い人",
    reason: "高速スクロール、横スクロール、アプリ別のボタン設定を使える右手用マウスです。機能数より、手に合うか、普段の操作を本当に減らせるかを先に確認します。左右対称や小型を好む人には別製品が向きます。",
    checks: ["右手用形状と手の大きさ", "Bluetooth / Logi Bolt", "設定ソフトを使うか"],
    sourceId: "logicool-mx-master-3s-official",
    officialUrl: "https://www.logicool.co.jp/ja-jp/shop/p/mx-master-3s",
    amazonUrl: "https://www.amazon.co.jp/s?k=Logicool+MX+Master+3S&tag=saunastampral-22",
  },
  {
    id: "flexispot-e7",
    image: "/shop/standing-desk-illustration.svg",
    imageAlt: "昇降デスクの編集部作成イメージ（実際の商品写真ではありません）",
    imageCredit: "画像：manapick編集部作成イメージ（実物と異なります）",
    category: "学習環境・姿勢",
    maker: "FLEXISPOT",
    name: "FLEXISPOT E7",
    fit: "調査・学習・制作が長時間になり、座位と立位を切り替えたい人",
    reason: "机を替えること自体は学習成果ではありません。E7は電動昇降で姿勢を切り替えられるため、すでに長時間の机作業があり、休憩と姿勢変更の習慣を作りたい場合に検討する道具です。",
    checks: ["天板と部屋の奥行き", "体格に合う昇降範囲", "搬入と組み立て場所"],
    sourceId: "flexispot-e7-official",
    officialUrl: "https://www.flexispot.jp/standing-desk-E7-family",
    amazonUrl: "https://www.amazon.co.jp/s?k=FLEXISPOT+E7+%E9%9B%BB%E5%8B%95%E6%98%87%E9%99%8D%E3%83%87%E3%82%B9%E3%82%AF&tag=saunastampral-22",
  },
] as const;
